name: ChebTools
dependencies:
  - python=3.6   # or 2.7
  - matplotlib
  - scipy
  #- jupyter # for local testing, uncomment, for binder, not needed
  #- notebook # for local testing, uncomment, for binder, not needed
  - pip:
    - "git+git://github.com/usnistgov/ChebTools.git"